name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: SCA safety
      continue-on-error: true
      run: |
        safety check --save-json safety-output.json

    - name: SAST bandit
      continue-on-error: true
      run: |
        bandit -r $GITHUB_WORKSPACE -f json -o bandit-result.json
        
        
    

